### ISSUE TITLE
 Document Upload & Task Points Update

### ISSUE THREAD

**Issue by GrirZouhair** [GrirZouhair/TaskManager#2]
### **Task 1:**

Implement proof document upload functionality in the employee dashboard upon clicking the black arrow.
Store the uploaded document in the "proof_document" field of the corresponding task in the database.
**### Task 2:**

In the backend, update the "points" field of a task based on its status and completion time:
If the task status is "fait" (completed) and finished within the deadline, add 10 points.
Otherwise, if completed after the deadline, only add 5 points.
This update should be done in the EmployeeAuthController on the /tasks/{id} route.
Refer to pages/EmployeePages/EmployeeDashboard/ for the frontend code and modify the update method in the TaskController on the backend.
Remember to follow the established Git workflow before starting work on these tasks:

Clone the repository if it's your first time.
Pull the latest changes from the remote repository.
Create a new branch for your work (recommended).
Implement the changes according to the description.
Commit your changes regularly with descriptive messages.
Create a pull request for code review and merging into the main branch.

**Comment by Code-With-Amine** [comment]
I already completed Task 2
